import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google'
import "./globals.css";
const dmSans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "AgencyCentral Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
        <link rel="icon" href="/favicon/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </head>
        <body className={dmSans.className}>{children}</body>
    </html>
  )
}